	var en = {
				// Reiter System-Einstellungen
				system_settings:"System settings",
				unit:"Unit",
				german:"German",
				english:"English",
				fahrenheit:"Fahrenheit",
				celsius:"Celsius",
				language:"Language",
				hostname:"Hostname",
				ap_name:"APN",
				hw_version:"Hardware version",
				update_search:"Automatically check for updates",
				prerelease:"Include prerelease in the search",
				// Reiter Display-Einstellungen
				display_settings:"Display settings",
				rotate_display:"Rotate display",
				calibrate_touch:"Calibrate touch",
				// Buttons
				back:"Back",
				save:"Save",
				//Kanaleinstellungen
				channel_name:"Channel name",
				temp_max:"Upper temperature limit",
				temp_min:"Lower temperature limit",
				temp_sensor:"Probe type",
				color:"Color",
				push_alarm:"Push alarm",
				buzzer_alarm:"Buzzer alarm",
				channel_delete:"Delete channel",
				channel_delete_msg:"Shall the channel really be deleted?",
				//Menü
				menuHome:"Home",
				menuWlan:"WLAN",
				menuSystem:"System",
				menuPitmaster:"Pitmaster",
				menuIOT:"IoT",
				menuHistory:"History",
				menuNotification:"Push Notification",
				menuAbout:"About",
				//History
				btnSaveChart:"Save chart",
				historyTitle:"History",
				date:"Date",
				historyTableName:"Name",
				//Menü About
				aboutTitle:"WLANThermo Team",
				forumTitle:"WLANThermo Forum",
				forumUrl:"Visit us in our forum!",
				//Menü Notification
				notificationTitle:"Notification service",
				notificationActivate:"Activate push notification",
				notificationToken:"API Token/Key",
				notificationKey:"Chat ID / User Key",
				notificationService:"Service",
				repeadOnce:"1x",
				repeadThreeTimes:"3x",
				repeadFiveTimes:"5x",
				repeadTenTimes:"10x",
				notificationRepead:"Repeats",
				notificationSendMessage:"Send a test message",
				//Cloud
				cloudTitle:"Nano Cloud",
				cloudActivate:"Activate Nano Cloud",
				tenSeconds:"10 seconds",
				fifteenSeconds:"15 seconds",
				thirtySeconds:"30 seconds", 
				oneMinutes:"1 minutes",
				twoMinutes:"2 minutes",
				fiveMinutes:"5 minutes",			//   (wollen wir hier nur Zahlen machen und alles in Sekunden und dann Einheit zum Textfeld?)
				sendInterval:"Send interval", 
				cloudBtnToken:"Generate token",
				mqttTitle:"Private MQTT Client",		
				mqttActivate:"Activate MQTT Client",
				mqttHost:"MQTT Host",
				mqttPort:"MQTT Port",
				mqttUser:"MQTT User",
				mqttPwd:"MQTT Password",
				mqttQos:"QoS",
				// Menü WLAN
				wlanTitle:"WLAN settings",
				wlanActivate:"Activate WLAN",
				wlanNetwork:"Select network...",
				wlanClear:"Delete stored network data",
				wlanConnect:"Connect network",
				wlanSSID:"SSID",
				wlanPwd:"Password",
				// Menü Pitmaster
				pitTitle:"Pitmaster settings",
				pitPitmaster:"Pitmaster",
				pitProfile:"Profile",
				pitChannel:"Channel",
				pitTemp:"Set temperature",
				pitValue:"Pitmaster value (%)",
				pitProfileName:"Profile name",
				pitAktorTitle:"Actuator",	
				pitAktor:"Actuator",
				pitDCmin:"DCmin [0-100%]",
				pitDCmax:"DCmax [0-100%]",
				pitSPmin:"SPmin [0-100%]",
				pitSPmax:"SPmax [0-100%]",
				pidTitle:"PID",
				pidKp:"Kp",
				pidKi:"Ki",
				pidKd:"Kd",
				pidJump:"Jump Power [10-100%]",
				pidAutotune:"Auto tune",
				pitAdvancesTitle:"Advanced",
				pitNameTitle:"General",
				pitLid:"Lid monitoring",
				pitlink:"Linking Actuators",
				pitlinkdegressiv:"degressive",
				pitlinklinear:"linear"
			};
	var de = {
				// Reiter System-Einstellungen
				system_settings:"System-Einstellungen",
				unit:"Einheit",		
				german:"Deutsch",
				english:"Englisch",
				fahrenheit:"Fahrenheit",
				celsius:"Celsius",
				language:"Sprache",
				hostname:"Hostname",
				ap_name:"APN",
				hw_version:"Hardwareversion",
				update_search:"Automatisch nach Updates suchen",
				prerelease:"Beta-Versionen in der Suche mit einschießen",
				// Reiter Display-Einstellungen
				display_settings:"Display-Einstellungen",
				rotate_display:"Display drehen",
				calibrate_touch:"Touch kalibrieren",
				// Buttons
				back:"Zurück",
				save:"Speichern",
				//Kanaleinstellungen
				channel_name:"Kanalname",
				temp_max:"Temperatur-Obergrenze",
				temp_min:"Temperatur-Untergrenze",
				temp_sensor:"Fühlertyp",
				color:"Farbe",
				push_alarm:"Push-Alarm",
				buzzer_alarm:"Piepser-Alarm",
				channel_delete:"Kanal löschen",
				channel_delete_msg:"Soll der Kanal wirklich gelöscht werden?",
				//Menü
				menuHome:"Home",
				menuWlan:"WLAN",
				menuSystem:"System",
				menuPitmaster:"Pitmaster",
				menuIOT:"IoT",
				menuHistory:"Historie",
				menuNotification:"Benachrichtigung",
				menuAbout:"Über",
				//History
				btnSaveChart:"Chart speichern",
				historyTitle:"Historie",
				date:"Datum",
				historyTableName:"Name",
				//Menü About
				aboutTitle:"WLANThermo Team",
				forumTitle:"WLANThermo Forum",
				forumUrl:"Wir freuen uns über deinen Besuch im Forum!",
				//Menü Notification
				notificationTitle:"Benachrichtungsdienst",
				notificationActivate:"Push-Benachrichtung aktivieren",
				notificationToken:"API Token/Key",
				notificationKey:"Chat ID / User Key",
				notificationService:"Dienst",				
				repeadOnce:"1x",
				repeadThreeTimes:"3x",
				repeadFiveTimes:"5x",
				repeadTenTimes:"10x",
				notificationRepead:"Wiederholungen",
				notificationSendMessage:"Testnachricht senden",
				//Cloud
				cloudTitle:"Nano-Cloud",
				cloudActivate:"Nano-Cloud aktivieren",
				tenSeconds:"10 Sekunden",				// siehe Hinweis EN
				fifteenSeconds:"15 Sekunden",			
				thirtySeconds:"30 Sekunden",
				oneMinutes:"1 Minute",
				twoMinutes:"2 Minuten",
				fiveMinutes:"5 Minuten",
				sendInterval:"Sendeintervall",
				cloudBtnToken:"Token generieren",
				mqttTitle:"Privater MQTT Client",
				mqttActivate:"MQTT Client aktivieren",
				mqttHost:"MQTT Host",
				mqttPort:"MQTT Port",
				mqttUser:"MQTT Benutzer",
				mqttPwd:"MQTT Passwort",
				mqttQos:"QoS",
				// Menü WLAN
				wlanTitle:"WLAN-Einstellungen",
				wlanActivate:"WLAN aktivieren",
				wlanNetwork:"Netzwerk wählen...",
				wlanClear:"Netzwerkverbindungsdaten löschen",
				wlanConnect:"Netzwerk verbinden",
				wlanSSID:"SSID",
				wlanPwd:"Passwort",
				// Menü Pitmaster
				pitTitle:"Pitmaster-Einstellungen",
				pitPitmaster:"Pitmaster",
				pitProfile:"Profil",
				pitChannel:"Kanal",
				pitTemp:"Solltemperatur",
				pitValue:"Pitmaster-Wert (%)",
				pitProfileName:"Profil-Name",
				pitAktorTitle:"Aktorik",
				pitAktor:"Aktor",
				pitDCmin:"DCmin [0-100%]",
				pitDCmax:"DCmax [0-100%]",
				pitSPmin:"SPmin [0-100%]",
				pitSPmax:"SPmax [0-100%]",
				pidTitle:"PID",
				pidKp:"Kp",
				pidKi:"Ki",
				pidKd:"Kd",
				pidJump:"Jump Power [10-100%]",					
				pidAutotune:"Autotune",
				pitAdvancesTitle:"Spezialfunktionen",
				pitNameTitle:"Allgemein",		
				pitLid:"Deckelüberwachung",
				pitlink:"Aktorverknüfung",
				pitlinkdegressiv:"degressiv",
				pitlinklinear:"linear"					
			};