name: Nextion build

on:
  pull_request:
    branches: 
      - master
      - develop
  push:
    branches:    
      - develop

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Build nextion
      shell: pwsh
      run: |
        .\nextion\build.ps1
    - uses: actions/upload-artifact@v4
      with:
          name: nextion_artifacts
          path: ./nextion/artifacts
